### ISSUE TITLE
game lagg when shooting

### ISSUE THREAD

**Issue by MeCrafX** [Pinelog-Studios/AdditionalGuns#86] opened 2022-09-17 12:19 UTC
hello i recently updated to 1.19.2 and now the game lagg when i shoot a gun from this mod.

i found this mostly happen when shoot far away

(latest version)

**Comment by Autovw** [comment] 2022-09-17 12:30
Duplicate of #71 

We are aiming to fix this in the very next update.

**Closed by Autovw** 2022-09-17 12:30 UTC
Labels: duplicate
